import Dexie from 'dexie';
import {db,type Note,type NoteSnapshot} from '../data';
export type ProtectedData={version:1;salt:string;iv:string;data:string};
type SecretFields=Pick<Note,'title'|'content'|'drawing'>;
const keys=new Map<string,CryptoKey>();
const encode=(bytes:Uint8Array)=>btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''));
const decode=(text:string)=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
const derive=async(password:string,salt:string)=>{const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:decode(salt),iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])};
export const isLocked=(note:Note)=>!!note.protectedData&&!note.unlocked;
export const forgetPassword=(id:string)=>{keys.delete(id)};
export async function seal<T extends SecretFields>(id:string,note:T,salt:string,key=keys.get(id)):Promise<T&{protectedData:ProtectedData}>{if(!key)throw new Error('Сначала откройте заметку паролем');const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id)},key,new TextEncoder().encode(JSON.stringify({title:note.title,content:note.content,drawing:note.drawing})));return {...note,title:'Защищённая заметка',content:'',drawing:undefined,unlocked:undefined,protectedData:{version:1,salt,iv:encode(iv),data:encode(new Uint8Array(data))}}}
export async function unseal<T extends SecretFields&{protectedData?:ProtectedData}>(id:string,note:T,key=keys.get(id)):Promise<T>{if(!note.protectedData)return note;if(!key)throw new Error('Введите пароль');const box=note.protectedData;const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(box.iv),additionalData:new TextEncoder().encode(id)},key,decode(box.data));return {...note,...JSON.parse(new TextDecoder().decode(plain)),unlocked:true}}
export async function unlockNote(id:string,password:string){const note=await db.notes.get(id);if(!note)throw new Error('Заметка не найдена');if(!note.protectedData)return note;const key=await derive(password,note.protectedData.salt);let opened:Note;try{opened=await unseal(id,note,key)}catch{throw new Error('Неверный пароль или повреждённая заметка')}keys.set(id,key);return opened}
export async function setNotePassword(id:string,password:string){if(password.length===0)throw new Error('Введите пароль');const salt=encode(crypto.getRandomValues(new Uint8Array(16))),key=await derive(password,salt);const saved=await db.transaction('rw',db.notes,db.noteRevisions,async()=>{const stored=await db.notes.get(id);if(!stored)throw new Error('Заметка не найдена');const note=await Dexie.waitFor(unseal(id,stored));const encrypted=await Dexie.waitFor(seal(id,note,salt,key));await db.notes.put(encrypted);for(const revision of await db.noteRevisions.where('noteId').equals(id).toArray()){const snapshot=await Dexie.waitFor(unseal(id,revision.snapshot));await db.noteRevisions.update(revision.id,{snapshot:await Dexie.waitFor(seal(id,snapshot,salt,key))})}return encrypted});keys.delete(id);return saved}
export async function removeNotePassword(id:string){const note=await db.transaction('rw',db.notes,db.noteRevisions,async()=>{const stored=await db.notes.get(id);if(!stored)throw new Error('Заметка не найдена');const opened=await Dexie.waitFor(unseal(id,stored));const clean={...opened,protectedData:undefined,unlocked:undefined};await db.notes.put(clean);for(const revision of await db.noteRevisions.where('noteId').equals(id).toArray()){const snapshot=await Dexie.waitFor(unseal(id,revision.snapshot));await db.noteRevisions.update(revision.id,{snapshot:{...snapshot,protectedData:undefined,unlocked:undefined}})}return clean});keys.delete(id);return note}
export const protectForStorage=(id:string,note:Note)=>note.protectedData?seal(id,note,note.protectedData.salt):Promise.resolve(note);
export const protectSnapshot=(note:Note,snapshot:NoteSnapshot)=>note.protectedData?seal(note.id,snapshot,note.protectedData.salt):Promise.resolve(snapshot);
export const canDecrypt=(id:string)=>keys.has(id);
