import {useState} from 'react';
import {createPortal} from 'react-dom';
import {LockKeyhole,Unlock,X} from 'lucide-react';
import {db,type Note} from '../data';
import {saveDraft} from '../noteEditing';
import {forgetPassword,removeNotePassword,setNotePassword,unlockNote} from './noteProtection';
import './protection.css';
export function UnlockNote({note,onChange,onClose}:{note:Note;onChange:(n:Note)=>void;onClose:()=>void}){const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="note-lock-screen"><LockKeyhole size={30}/><h2>Заметка защищена</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{onChange(await unlockNote(note.id,password))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}}><input autoFocus type="password" aria-label="Пароль заметки" placeholder="Пароль" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p role="alert">{error}</p>}<button disabled={busy}>Открыть</button><button type="button" onClick={onClose}>Закрыть</button></form></div>}
export default function PasswordButton({note,onChange}:{note:Note;onChange:(n:Note)=>void}){const [open,setOpen]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const run=async(action:()=>Promise<Note>)=>{setBusy(true);setError('');try{await saveDraft(note);const updated=await action();onChange(updated);setOpen(false);setPassword('')}catch(error){setError((error as Error).message)}finally{setBusy(false)}};return <><button className="password-button" title={note.protectedData?'Защита заметки':'Установить пароль'} aria-label={note.protectedData?'Защита заметки':'Установить пароль'} onClick={()=>{setError('');setOpen(true)}}><LockKeyhole size={21}/></button>{open&&createPortal(<div className="password-overlay" onMouseDown={e=>e.stopPropagation()}><section className="password-dialog" onKeyDown={e=>{if(e.key==='Escape'&&!busy){setOpen(false);setPassword('')}if(e.key==='Tab'){const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input'));const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}} role="dialog" aria-modal="true" aria-label="Пароль заметки"><div className="password-heading"><LockKeyhole size={22}/><strong>{note.protectedData?'Защита заметки':'Установить пароль'}</strong><button aria-label="Закрыть настройки пароля" disabled={busy} onClick={()=>{setOpen(false);setPassword('')}}><X size={20}/></button></div><form onSubmit={e=>{e.preventDefault();void run(()=>setNotePassword(note.id,password))}}><input autoFocus aria-label="Новый пароль" type="password" autoComplete="new-password" placeholder="Любой пароль" value={password} onChange={e=>setPassword(e.target.value)}/><p>Любая длина и символы. Без пароля восстановить текст и рисунок не получится.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy||password.length===0}>{note.protectedData?'Изменить пароль':'Установить пароль'}</button></form>{note.protectedData&&<div className="password-actions"><button disabled={busy} onClick={()=>void run(async()=>{forgetPassword(note.id);return (await db.notes.get(note.id))!})}><LockKeyhole size={16}/> Закрыть замок</button><button disabled={busy} onClick={()=>void run(()=>removeNotePassword(note.id))}><Unlock size={16}/> Убрать пароль</button></div>}</section></div>,document.body)}</>}
