import {useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ImagePlus,Trash2,X,RotateCcw,LockKeyhole} from 'lucide-react';
import {type Note} from '../data';
import {UnlockNote} from '../protection/PasswordButton';
import {forgetPassword,isLocked} from '../protection/noteProtection';
import {readPhoto,changePhotoTrash,purgePhotoTrash,restorePhoto,type NotePhoto} from './photoRepository';
import './photos.css';
type EditProps={note:Note;onChange:(note:Note)=>void|Promise<void>};
export function PhotoButton({note,onChange}:EditProps){const input=useRef<HTMLInputElement>(null),latest=useRef(note);latest.current=note;const [busy,setBusy]=useState(false),[error,setError]=useState('');return <><button className="photo-add" title="Добавить фото" aria-label="Добавить фото" disabled={busy} onClick={()=>input.current?.click()}><ImagePlus size={22}/></button><input ref={input} type="file" hidden multiple accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/bmp" onChange={async e=>{const files=Array.from(e.target.files??[]);e.target.value='';if(!files.length)return;setBusy(true);setError('');try{const photos=[];for(const file of files)photos.push(await readPhoto(file));await onChange({...latest.current,photos:[...(latest.current.photos??[]),...photos]})}catch(error){setError((error as Error).message)}finally{setBusy(false)}}}/>{error&&<span className="photo-error" role="alert">{error}</span>}</>}
export function PhotoPreview({photos}:{photos?:NotePhoto[]}){const first=photos?.find(p=>p.deletedAt===null);return first?<img className="photo-card-preview" src={first.src} alt="Фото в заметке" loading="lazy"/>:null}
export function PhotoGallery({note,onChange}:EditProps){const [view,setView]=useState<string>(),[error,setError]=useState('');const photos=(note.photos??[]).filter(p=>p.deletedAt===null),opened=photos.find(p=>p.id===view);const remove=async(photo:NotePhoto)=>{try{await onChange(changePhotoTrash(note,photo.id,Date.now()));setView(undefined);setError('')}catch(e){setError((e as Error).message)}};return <>{error&&<p role="alert">{error}</p>}<div className="note-photos">{photos.map(photo=><div className="note-photo" key={photo.id}><button className="photo-open" aria-label={'Открыть фото '+photo.name} onClick={()=>setView(photo.id)}><img src={photo.src} alt={photo.name} loading="lazy"/></button><button className="photo-trash" title="В корзину" aria-label={'Удалить фото '+photo.name} onClick={()=>remove(photo)}><Trash2 size={17}/></button></div>)}</div>{opened&&createPortal(<PhotoViewer photo={opened} onClose={()=>setView(undefined)} onDelete={()=>remove(opened)}/>,document.body)}</>}
function PhotoViewer({photo,onClose,onDelete}:{photo:NotePhoto;onClose:()=>void;onDelete?:()=>void}){return <div className="photo-viewer" role="dialog" aria-modal="true" aria-label="Просмотр фото" onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button'));const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><div className="photo-viewer-header"><span>{photo.name}</span>{onDelete&&<button aria-label="Удалить открытое фото" title="В корзину" onClick={onDelete}><Trash2 size={21}/></button>}<button autoFocus aria-label="Закрыть фото" onClick={onClose}><X size={24}/></button></div><img className="photo-full" src={photo.src} alt={photo.name}/></div>}
export function PhotoTrash({notes,onChanged}:{notes:Note[];onChanged:()=>void|Promise<unknown>}){const [opened,setOpened]=useState<Note>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<NotePhoto>();const candidates=notes.filter(n=>n.photoTrashCount||(n.photos??[]).some(p=>p.deletedAt!==null));const close=()=>{if(opened)forgetPassword(opened.id);setOpened(undefined)};const restore=async(note:Note,id:string)=>{setBusy(true);try{const updated=await restorePhoto(note.id,id);if(opened?.id===note.id)setOpened(updated);await onChanged();setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};const purge=async(note:Note)=>{if(!confirm('Удалить фотографии из корзины этой заметки навсегда? Восстановить их в приложении будет нельзя.'))return;setBusy(true);try{const updated=await purgePhotoTrash(note.id);if(opened?.id===note.id)setOpened(updated);await onChanged();setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};const group=(note:Note)=><section className="photo-trash-group" key={note.id}><div className="photo-trash-heading"><h3>{note.title||'Без названия'}</h3><button disabled={busy} onClick={()=>void purge(note)}>Очистить корзину фото</button></div><div className="note-photos">{(note.photos??[]).filter(p=>p.deletedAt!==null).map(photo=><div className="note-photo" key={photo.id}><button className="photo-open" aria-label={'Посмотреть удалённое фото '+photo.name} onClick={()=>setPreview(photo)}><img src={photo.src} alt={photo.name}/></button><button className="photo-restore" disabled={busy} onClick={()=>void restore(note,photo.id)}><RotateCcw size={16}/> Восстановить</button></div>)}</div></section>;return <section className="photo-trash-section"><h2>Фотографии в корзине</h2>{error&&<p role="alert">{error}</p>}{!candidates.length?<p>Удалённых фотографий нет.</p>:candidates.map(note=>isLocked(note)?<button className="photo-locked-trash" key={note.id} onClick={()=>setOpened(note)}><LockKeyhole size={18}/> Фото защищённой заметки ({note.photoTrashCount??0})</button>:group(note))}{opened&&createPortal(<div className="photo-trash-overlay" onMouseDown={e=>e.stopPropagation()}>{isLocked(opened)?<UnlockNote note={opened} onChange={setOpened} onClose={close}/>:<section className="photo-trash-dialog"><button className="photo-trash-close" onClick={close}>Закрыть</button>{group(opened)}</section>}</div>,document.body)}{preview&&createPortal(<PhotoViewer photo={preview} onClose={()=>setPreview(undefined)}/>,document.body)}</section>}
