import Dexie from 'dexie';
import {db,type Note} from '../data';
import {updateNoteFields} from '../noteUpdateService';
import {unseal,protectSnapshot} from '../protection/noteProtection';
export type NotePhoto={id:string;name:string;mime:string;src:string;width:number;height:number;createdAt:number;deletedAt:number|null};
export const photoTrashCount=(photos:NotePhoto[]=[])=>photos.filter(p=>p.deletedAt!==null).length;
export const changePhotoTrash=(note:Note,id:string,deletedAt:number|null):Note=>({...note,photos:(note.photos??[]).map(p=>p.id===id?{...p,deletedAt}:p)});
export async function readPhoto(file:File):Promise<NotePhoto>{if(!/^image\/(jpeg|png|webp|gif|avif|bmp)$/.test(file.type))throw new Error('Поддерживаются JPEG, PNG, WebP, GIF, AVIF и BMP');const src=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Не удалось прочитать фото'));reader.readAsDataURL(file)});const image=new Image();image.src=src;try{await image.decode()}catch{throw new Error('Не удалось открыть изображение '+file.name)}return {id:crypto.randomUUID(),name:file.name,mime:file.type,src,width:image.naturalWidth,height:image.naturalHeight,createdAt:Date.now(),deletedAt:null}}
export async function restorePhoto(noteId:string,photoId:string){return db.transaction('rw',db.notes,db.noteRevisions,async()=>{const stored=await db.notes.get(noteId);if(!stored)throw new Error('Заметка не найдена');const note=await Dexie.waitFor(unseal(noteId,stored));if(!note.photos?.some(p=>p.id===photoId))throw new Error('Фото уже удалено из корзины');return updateNoteFields(noteId,{photos:changePhotoTrash(note,photoId,null).photos,deletedAt:null})})}
/** Purge only trashed photos and remove their copies from revision history atomically. */
export async function purgePhotoTrash(noteId:string){return db.transaction('rw',db.notes,db.noteRevisions,db.tombstones,async()=>{const stored=await db.notes.get(noteId);if(!stored)throw new Error('Заметка не найдена');const note=await Dexie.waitFor(unseal(noteId,stored)),ids=new Set((note.photos??[]).filter(p=>p.deletedAt!==null).map(p=>p.id));if(!ids.size)return note;const updated=await updateNoteFields(noteId,{photos:(note.photos??[]).filter(p=>!ids.has(p.id))});for(const revision of await db.noteRevisions.where('noteId').equals(noteId).toArray()){const snapshot=await Dexie.waitFor(unseal(noteId,revision.snapshot));if(snapshot.photos?.some(p=>ids.has(p.id)))await db.noteRevisions.update(revision.id,{snapshot:await Dexie.waitFor(protectSnapshot(updated,{...snapshot,photos:snapshot.photos.filter(p=>!ids.has(p.id)),photoTrashCount:photoTrashCount(snapshot.photos.filter(p=>!ids.has(p.id)))}))})}for(const id of ids)await db.tombstones.put({id:'photo:'+id,entityType:'photo',entityId:id,deletedAt:Date.now()});return updated})}
