import Dexie, { type Table } from 'dexie';
export type NoteColor = 'default'|'green'|'yellow'|'blue'|'pink'|'purple'|'gray';
export type Note = { id:string; pomodoroMinutes?:number; title:string; content:string; color:NoteColor; createdAt:number; updatedAt:number; archivedAt:number|null; deletedAt:number|null; inInbox:boolean; inToday:boolean; parentId:string|null; isProject:boolean; trackTime:boolean; goalEnabled:boolean; targetHours:number|null; deadline:string|null; goalStartDate:string|null; actualHoursAtGoalStart:number; goalUpdatedAt:number|null };
export type NoteSnapshot = Omit<Note,'id'|'createdAt'|'updatedAt'|'archivedAt'|'deletedAt'>;
export type RevisionReason = 'content'|'appearance'|'planning'|'move'|'tracking'|'goal'|'restore'|'copy-content'|'mixed';
export type NoteRevision = { id:string; noteId:string; snapshot:NoteSnapshot; createdAt:number; reason:RevisionReason };
export type WorkspaceMeta = { id:'workspace'; workspaceId:string; deviceId:string; schemaVersion:number; createdAt:number; updatedAt:number };
export type Tombstone = { id:string; entityType:'note'|'trackingSession'; entityId:string; deletedAt:number };
export type TrackingStatus = 'running'|'paused'|'completed';
export type TrackingSession = { id:string; noteId:string; startedAt:number|null; endedAt:number|null; durationMs:number; status:TrackingStatus; createdAt:number; updatedAt:number; manual:boolean; date:number; comment?:string; pomodoro?: import('./pomodoro').PomodoroState };
class NomaDB extends Dexie { notes!:Table<Note,string>; trackingSessions!:Table<TrackingSession,string>; noteRevisions!:Table<NoteRevision,string>; workspaceMeta!:Table<WorkspaceMeta,'workspace'>; tombstones!:Table<Tombstone,string>; constructor(){super('noma');this.version(1).stores({notes:'id, updatedAt, archivedAt, deletedAt, inInbox, inToday, parentId'});this.version(2).stores({notes:'id, updatedAt, archivedAt, deletedAt, inInbox, inToday, parentId, isProject'}).upgrade(tx=>tx.table('notes').toCollection().modify((note:Note)=>{note.isProject=note.isProject??false}));this.version(3).stores({notes:'id, updatedAt, archivedAt, deletedAt, inInbox, inToday, parentId, isProject, trackTime',trackingSessions:'id, noteId, status, date, updatedAt'}).upgrade(tx=>tx.table('notes').toCollection().modify((note:Note)=>{note.trackTime=note.trackTime??false}));this.version(4).stores({notes:'id, updatedAt, archivedAt, deletedAt, inInbox, inToday, parentId, isProject, trackTime',trackingSessions:'id, noteId, status, date, updatedAt'}).upgrade(tx=>tx.table('notes').toCollection().modify((note:Note)=>{note.goalEnabled=note.goalEnabled??false;note.targetHours=note.targetHours??null;note.deadline=note.deadline??null;note.goalStartDate=note.goalStartDate??null;note.actualHoursAtGoalStart=note.actualHoursAtGoalStart??0;note.goalUpdatedAt=note.goalUpdatedAt??null}));this.version(5).stores({notes:'id, updatedAt, archivedAt, deletedAt, inInbox, inToday, parentId, isProject, trackTime',trackingSessions:'id, noteId, status, date, updatedAt',noteRevisions:'id, noteId, createdAt'});this.version(6).stores({notes:'id, updatedAt, archivedAt, deletedAt, inInbox, inToday, parentId, isProject, trackTime',trackingSessions:'id, noteId, status, date, updatedAt',noteRevisions:'id, noteId, createdAt',workspaceMeta:'id',tombstones:'id, entityType, entityId, deletedAt'})} }
export const db=new NomaDB();
export const newNote=(extra:Partial<Note>={}):Note=>{const now=Date.now();return {id:crypto.randomUUID(),title:'',content:'',color:'default',createdAt:now,updatedAt:now,archivedAt:null,deletedAt:null,inInbox:false,inToday:false,parentId:null,isProject:false,trackTime:false,goalEnabled:false,targetHours:null,deadline:null,goalStartDate:null,actualHoursAtGoalStart:0,goalUpdatedAt:null,...extra}};
export const searchNotes=(notes:Note[],q:string)=>{const s=q.trim().toLowerCase();return !s?notes:notes.filter(n=>`${n.title} ${n.content}`.toLowerCase().includes(s))};
