import { useEffect,useState } from 'react';import { db,type Note } from './data';import { calculateGoalMetrics,saveGoal } from './goalRepository';import { getSessionsForNote } from './trackingRepository';import { updateNoteFields } from './noteUpdateService';
export default function GoalPanel({note,onChange}:{note:Note;onChange:(n:Note)=>void}){const [hours,setHours]=useState(note.targetHours?String(note.targetHours):''),[deadline,setDeadline]=useState(note.deadline||''),[metrics,setMetrics]=useState<ReturnType<typeof calculateGoalMetrics>>(),[open,setOpen]=useState(note.goalEnabled),[expanded,setExpanded]=useState(true),[editing,setEditing]=useState(false);const goalSessions=async()=>{const all=await db.notes.toArray(),ids=new Set([note.id]);let changed=true;while(changed){changed=false;for(const n of all)if(n.parentId&&ids.has(n.parentId)&&!ids.has(n.id)){ids.add(n.id);changed=true}}return (await Promise.all([...ids].map(id=>getSessionsForNote(id)))).flat()};const load=async()=>{if(note.goalEnabled&&note.targetHours&&note.deadline&&note.goalStartDate){const sessions=await goalSessions(),goal={targetHours:note.targetHours,deadline:note.deadline,goalStartDate:note.goalStartDate,actualHoursAtGoalStart:note.actualHoursAtGoalStart};setMetrics(calculateGoalMetrics(goal,sessions));}};useEffect(()=>{load()},[note]);const save=async()=>{const target=Number(hours),today=new Date().toISOString().slice(0,10);if(!Number.isFinite(target)||target<=0||!deadline||deadline<today)return;const updated=await saveGoal(note,target,deadline,today);onChange(updated);setOpen(true);setEditing(false)};const remove=async()=>{const updated={...note,goalEnabled:false,targetHours:null,deadline:null,goalStartDate:null,actualHoursAtGoalStart:0,goalUpdatedAt:null,updatedAt:Date.now()};const saved=await updateNoteFields(note.id,{goalEnabled:false,targetHours:null,deadline:null,goalStartDate:null,actualHoursAtGoalStart:0,goalUpdatedAt:null});onChange(saved);setOpen(false)};if(!open)return <section className="goal-panel goal-collapsed"><button onClick={()=>setOpen(true)}>＋ Добавить цель</button></section>;return <section className="goal-panel"><div className="goal-head"><strong>Цель</strong>{note.goalEnabled&&<span>{expanded&&<><button onClick={()=>setEditing(true)}>Изменить</button> <button onClick={remove}>Удалить цель</button></>}<button onClick={()=>setExpanded(v=>!v)}>{expanded?"Свернуть":"Развернуть"}</button></span>}</div>{(!note.goalEnabled||editing)?<div className="goal-form"><input type="number" min="0.1" step="0.1" placeholder="Целевые часы" value={hours} onChange={e=>setHours(e.target.value)}/><input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/><button onClick={save}>Сохранить цель</button><button onClick={()=>setEditing(false)}>Отмена</button></div>:expanded&&<><div className="goal-metrics"><span>Цель <b>{note.targetHours} ч</b> до {note.deadline}</span>{metrics&&<span>Осталось <b>{metrics.remainingHours.toFixed(1)} ч</b></span>}</div></>}</section>}








