import type { TrackingSession } from './data';
export type GoalMetrics={actualHours:number;remainingHours:number;remainingDays:number;requiredHoursPerDay:number;plannedHoursByToday:number;aheadBehindHours:number;progressPercent:number;projectedCompletionDate:string|null;completed:boolean;overdue:boolean};
const day=(value:string|Date)=>{const d=typeof value==='string'?new Date(`${value}T00:00:00`):new Date(value);return new Date(d.getFullYear(),d.getMonth(),d.getDate())};
export const localDate=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),date=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${date}`};
export const calendarDays=(from:string,to:string)=>Math.max(0,Math.round((day(to).getTime()-day(from).getTime())/86400000)+1);
export const actualHours=(sessions:TrackingSession[],now=Date.now())=>sessions.reduce((sum,s)=>sum+s.durationMs+(s.status==='running'&&s.startedAt?s.startedAt?Math.max(0,now-s.startedAt):0:0),0)/3600000;
export const calculateGoalMetrics=(goal:{targetHours:number;deadline:string;goalStartDate:string;actualHoursAtGoalStart:number},sessions:TrackingSession[],today=localDate(new Date()),now=Date.now()):GoalMetrics=>{const actual=goal.actualHoursAtGoalStart+actualHours(sessions,now);const remaining=Math.max(goal.targetHours-actual,0);const days=calendarDays(today,goal.deadline);const required=days>0?remaining/days:remaining;const elapsed=Math.max(1,calendarDays(goal.goalStartDate,today));const planned=goal.actualHoursAtGoalStart+(goal.targetHours-goal.actualHoursAtGoalStart)*Math.min(1,Math.max(0,(elapsed-1)/Math.max(1,calendarDays(goal.goalStartDate,goal.deadline)-1)));const ahead=actual-planned;const completed=actual>=goal.targetHours;const overdue=!completed&&day(goal.deadline)<day(today);const average=(actual-goal.actualHoursAtGoalStart)/elapsed;const projected=average>0&&!completed?localDate(new Date(day(today).getTime()+Math.ceil(remaining/average)*86400000)):null;return {actualHours:actual,remainingHours:remaining,remainingDays:days,requiredHoursPerDay:completed?0:required,plannedHoursByToday:planned,aheadBehindHours:ahead,progressPercent:goal.targetHours>0?actual/goal.targetHours*100:0,projectedCompletionDate:projected,completed,overdue}};
export const buildPlanSeries=(goal:{targetHours:number;goalStartDate:string;deadline:string;actualHoursAtGoalStart:number})=>{const count=calendarDays(goal.goalStartDate,goal.deadline);return Array.from({length:count},(_,i)=>({date:localDate(new Date(day(goal.goalStartDate).getTime()+i*86400000)),hours:goal.actualHoursAtGoalStart+(goal.targetHours-goal.actualHoursAtGoalStart)*(count===1?1:i/(count-1))}))};
export const buildActualSeries=(sessions:TrackingSession[],goalStartDate:string)=>{const grouped=new Map<string,number>();for(const s of sessions){const date=localDate(new Date(s.date));grouped.set(date,(grouped.get(date)||0)+s.durationMs/3600000)}let total=0;return [...grouped.keys()].sort().map(date=>{total+=grouped.get(date)!;return {date,hours:total}}).filter(p=>p.date>=goalStartDate)};
