import 'fake-indexeddb/auto';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { db,newNote } from './data';
import { saveGoal } from './goalRepository';
import { archiveNote,permanentlyDeleteNote,restoreArchive,restoreTrash,trashNote } from './noteRepository';
import { REVISION_LIMIT,copyContentFromRevision,createRevision,getRevisions,restoreRevision } from './noteRevisionRepository';
import { updateNoteFields } from './noteUpdateService';
import { addManualEntry,setTrackingEnabled } from './trackingRepository';
import { createChildProject,moveNote,permanentlyDeleteSubtree } from './treeRepository';

let clock=Date.parse('2099-01-01T10:00:00Z');
beforeEach(async()=>{clock=Date.parse('2099-01-01T10:00:00Z');vi.spyOn(Date,'now').mockImplementation(()=>clock);await db.notes.clear();await db.noteRevisions.clear();await db.trackingSessions.clear()});
afterEach(()=>vi.restoreAllMocks());
const add=async(extra={})=>{const note=newNote(extra);await db.notes.add(note);return note};

describe('snapshot note revision history',()=>{
 it('does not create a revision while creating a Note',async()=>{const note=await add({title:'New'});expect(await getRevisions(note.id)).toHaveLength(0)});
 it('captures the previous state for a first meaningful update',async()=>{const note=await add({title:'A',content:'First'});await updateNoteFields(note.id,{title:'B'});const [revision]=await getRevisions(note.id);expect(revision.snapshot.title).toBe('A');expect(revision.snapshot.content).toBe('First')});
 it('does not create a revision for an unchanged update',async()=>{const note=await add({title:'A'});await updateNoteFields(note.id,{title:'A'});expect(await getRevisions(note.id)).toHaveLength(0)});
 it('does not version Archive, Trash, or their lifecycle restores',async()=>{const note=await add({title:'A'});await archiveNote(note);await restoreArchive(note);await trashNote(note);await restoreTrash(note);expect(await getRevisions(note.id)).toHaveLength(0)});
 it('records multiple changed fields as one logical snapshot',async()=>{const note=await add({title:'A',content:'One'});await updateNoteFields(note.id,{title:'B',content:'Two',color:'blue'});const revisions=await getRevisions(note.id);expect(revisions).toHaveLength(1);expect(revisions[0].snapshot).toMatchObject({title:'A',content:'One',color:'default'})});
 it('coalesces a short autosave series without revision spam',async()=>{const note=await add();await updateNoteFields(note.id,{title:'A'});clock+=1000;await updateNoteFields(note.id,{content:'B'});expect(await getRevisions(note.id)).toHaveLength(1);clock+=3*60*1000+1;await updateNoteFields(note.id,{color:'green'});expect(await getRevisions(note.id)).toHaveLength(2)});
 it('versions title, content, color, Today, Inbox and tracking capability',async()=>{const note=await add();await updateNoteFields(note.id,{title:'T',content:'C',color:'pink',inToday:true,inInbox:true});clock+=3*60*1000+1;await setTrackingEnabled(note.id,true);const revisions=await getRevisions(note.id);expect(revisions).toHaveLength(2);expect(revisions[0].snapshot).toMatchObject({title:'T',content:'C',color:'pink',inToday:true,inInbox:true,trackTime:false})});
 it('versions movement through the canonical tree flow',async()=>{const project=await createChildProject(null),note=await add();await moveNote(note.id,project);const [revision]=await getRevisions(note.id);expect(revision.snapshot.parentId).toBeNull()});
 it('versions a goal change as a single snapshot',async()=>{const note=await add({title:'Goal'});await saveGoal(note,12,'2099-02-01','2099-01-01');const revisions=await getRevisions(note.id);expect(revisions).toHaveLength(1);expect(revisions[0].snapshot.goalEnabled).toBe(false)});
 it('persists revisions after a re-read',async()=>{const note=await add({title:'Before'});await updateNoteFields(note.id,{title:'After'});const reloaded=await db.notes.get(note.id);expect((await getRevisions(reloaded!.id))[0].snapshot.title).toBe('Before')});
 it('restores a prior version and preserves current state as a revision',async()=>{const note=await add({title:'A',content:'One'});await updateNoteFields(note.id,{title:'B',content:'Two'});clock+=3*60*1000+1;await updateNoteFields(note.id,{title:'C',content:'Three'});const revision=(await getRevisions(note.id)).find(item=>item.snapshot.title==='A')!;const restored=await restoreRevision(note.id,revision.id);expect(restored).toMatchObject({id:note.id,title:'A',content:'One'});expect((await getRevisions(note.id)).some(item=>item.snapshot.title==='C')).toBe(true)});
 it('restore keeps tracking sessions and the same note id',async()=>{const note=await add({title:'A'});await addManualEntry(note.id,60_000);await updateNoteFields(note.id,{title:'B'});const revision=(await getRevisions(note.id))[0];const restored=await restoreRevision(note.id,revision.id);expect(restored.id).toBe(note.id);expect(await db.trackingSessions.where('noteId').equals(note.id).count()).toBe(1)});
 it('copies only title and content from a historical version',async()=>{const note=await add({title:'A',content:'Old',color:'green',parentId:'parent',trackTime:true});await updateNoteFields(note.id,{title:'B',content:'New'});const revision=(await getRevisions(note.id))[0];await updateNoteFields(note.id,{color:'pink',parentId:null,trackTime:false});const copied=await copyContentFromRevision(note.id,revision.id);expect(copied).toMatchObject({title:'A',content:'Old',color:'pink',parentId:null,trackTime:false})});
 it('trims oldest revisions first at the 100 revision limit',async()=>{const note=await add();for(let index=0;index<=REVISION_LIMIT;index++)await createRevision(note,'content',index);const revisions=await getRevisions(note.id);expect(revisions).toHaveLength(REVISION_LIMIT);expect(revisions.at(-1)?.createdAt).toBe(1);expect(revisions[0].createdAt).toBe(REVISION_LIMIT)});
 it('permanent Note delete removes its revisions',async()=>{const note=await add();await updateNoteFields(note.id,{title:'Changed'});await permanentlyDeleteNote(note.id);expect(await getRevisions(note.id)).toHaveLength(0)});
 it('permanent subtree delete removes revisions for every descendant',async()=>{const root=await createChildProject(null),child=await add({parentId:root});await updateNoteFields(root,{title:'Root'});await updateNoteFields(child.id,{title:'Child'});await permanentlyDeleteSubtree(root);expect(await getRevisions(root)).toHaveLength(0);expect(await getRevisions(child.id)).toHaveLength(0)});
 it('falls back to the current parent when a historical parent no longer exists',async()=>{const note=await add({parentId:null});const revision=await createRevision({...note,parentId:'gone'},'move');const restored=await restoreRevision(note.id,revision.id);expect(restored.parentId).toBeNull()});
 it('does not restore a parent that would create a cycle',async()=>{const root=await createChildProject(null),child=await createChildProject(root);const current=(await db.notes.get(root))!;const revision=await createRevision({...current,parentId:child},'move');const restored=await restoreRevision(root,revision.id);expect(restored.parentId).toBeNull();expect(await moveNote(child,root)).toBeTruthy()});
});
