import { useEffect, useState } from 'react';
import { ArrowLeft, Plus, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { db, type Note } from './data';
import { createChildNote, createChildProject, getAncestors, getChildren, moveNote, updateSubtree } from './treeRepository';
export default function ProjectView(){
 const {id}=useParams();const navigate=useNavigate();const [project,setProject]=useState<Note>();const [children,setChildren]=useState<Note[]>([]);const [crumbs,setCrumbs]=useState<Note[]>([]);const [projects,setProjects]=useState<Note[]>([]);const [moving,setMoving]=useState<Note>();
 const load=async()=>{if(!id)return;const p=(await db.notes.toArray()).find(n=>n.id===id);setProject(p);setChildren(await getChildren(id));setCrumbs(await getAncestors(id));setProjects((await db.notes.toArray()).filter(n=>n.isProject&&!n.deletedAt))};useEffect(()=>{load()},[id]);
 if(!project)return <main className="content"><button onClick={()=>navigate('/')}>Назад</button><h1>Проект не найден</h1></main>;
 const move=(parent:string|null)=>{if(!moving)return;moveNote(moving.id,parent).then(()=>{setMoving(undefined);load()}).catch(e=>alert(e instanceof Error?e.message:'Перемещение запрещено'))};
 const archiveTree=()=>{if(confirm('Архивировать проект и все вложенные элементы?'))updateSubtree(project.id,'archivedAt',Date.now()).then(()=>navigate('/archive'))};
 const trashTree=()=>{if(confirm('Переместить проект и все вложенные элементы в корзину?'))updateSubtree(project.id,'deletedAt',Date.now()).then(()=>navigate('/trash'))};
 return <main className={'content '+project.color}><button className="back" onClick={()=>navigate('/')}><ArrowLeft size={16}/> Все заметки</button><div className="breadcrumbs">{crumbs.map(c=><button key={c.id} onClick={()=>navigate('/project/'+c.id)}>{c.title||'Без названия'} › </button>)}<strong>{project.title||'Без названия'}</strong></div><h1>{project.title||'Без названия'}</h1><p>{project.content}</p><div className="project-actions"><button className="new" onClick={async()=>navigate('/note/'+await createChildNote(project.id))}><Plus size={16}/> Новая заметка</button><button onClick={async()=>navigate('/project/'+await createChildProject(project.id))}>Новый проект</button></div><div className="grid">{children.map(n=><article className={'card '+n.color} key={n.id} onClick={()=>navigate(n.isProject?'/project/'+n.id:'/note/'+n.id)}><h3>{n.isProject?'▣ ':''}{n.title||'Без названия'}</h3><p>{n.content||'Пусто'}</p><button onClick={e=>{e.stopPropagation();setMoving(n)}}>Переместить</button></article>)}</div>{moving&&<div className="overlay" onMouseDown={()=>setMoving(undefined)}><div className="settings" onMouseDown={e=>e.stopPropagation()}><div className="editor-top"><h2>Переместить</h2><button onClick={()=>setMoving(undefined)}><X size={18}/></button></div><p>Новое расположение: {moving.title||'Без названия'}</p><button onClick={()=>move(null)}>Корень — Все заметки</button>{projects.filter(p=>p.id!==moving.id).map(p=><button key={p.id} onClick={()=>move(p.id)}>▣ {p.title||'Без названия'}</button>)}</div></div>}</main>;
}
