import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {Pencil,PenTool,Highlighter,Eraser,Undo2,Redo2,Check} from 'lucide-react';
import {emptyDrawing,eraseAt,pathFor,type Drawing,type DrawingTool,type Point,type Stroke} from './model';
import './drawing.css';
export function DrawIcon(){return <svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m8 17 4-12 4 12-4-3-4 3Z" strokeLinejoin="round"/></svg>}
function Strokes({drawing}:{drawing:Drawing}){return <>{drawing.strokes.map(s=>s.points.length===1?<circle key={s.id} cx={s.points[0].x} cy={s.points[0].y} r={s.width/2} fill={s.color} opacity={s.opacity}/>:<path key={s.id} d={pathFor(s.points)} fill="none" stroke={s.color} strokeWidth={s.width} opacity={s.opacity} strokeLinecap="round" strokeLinejoin="round"/>)}</>}
export function DrawingPreview({drawing}:{drawing?:Drawing}){if(!drawing?.strokes.length)return null;return <svg className="drawing-preview" role="img" aria-label="Рисунок заметки" viewBox={`0 0 ${drawing.width} ${drawing.height}`}><Strokes drawing={drawing}/></svg>}
export default function DrawingButton({drawing,onChange}:{drawing?:Drawing;onChange:(drawing:Drawing)=>void}){const [open,setOpen]=useState(false);return <><button type="button" className="draw-launcher" aria-label="Рисовать" title="Рисовать" onClick={()=>setOpen(v=>!v)}><DrawIcon/></button>{open&&<DrawingEditor initial={drawing??emptyDrawing()} onChange={onChange} onClose={()=>setOpen(false)}/>}</>}
function DrawingEditor({initial,onChange,onClose}:{initial:Drawing;onChange:(d:Drawing)=>void;onClose:()=>void}){
 const [drawing,setDrawing]=useState(initial),[tool,setTool]=useState<DrawingTool>('pen'),[color,setColor]=useState('#252525'),[size,setSize]=useState(4),[undo,setUndo]=useState<Drawing[]>([]),[redo,setRedo]=useState<Drawing[]>([]);
 const value=useRef(initial),gesture=useRef<{pointerId:number;before:Drawing;stroke?:Stroke}|undefined>(undefined),lastSave=useRef(0),change=useRef(onChange);change.current=onChange;
 const emit=(d:Drawing)=>{value.current=d;setDrawing(d);change.current(d)};
 const finish=()=>{if(!gesture.current)return;const before=gesture.current.before;gesture.current=undefined;if(value.current!==before){setUndo(items=>[...items,before].slice(-100));setRedo([]);change.current(value.current)}};
 const close=()=>{finish();onClose()};
 const undoStroke=()=>{finish();const previous=undo[undo.length-1];if(previous){setRedo(items=>[...items,value.current]);setUndo(undo.slice(0,-1));emit(previous)}};
 const redoStroke=()=>{finish();const next=redo[redo.length-1];if(next){setUndo(items=>[...items,value.current]);setRedo(redo.slice(0,-1));emit(next)}};
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;return()=>previous?.focus()},[]);
 const point=(event:PointerEvent<SVGSVGElement>):Point=>{const matrix=event.currentTarget.getScreenCTM();const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix?.inverse());return {x:Math.max(0,Math.min(drawing.width,p.x)),y:Math.max(0,Math.min(drawing.height,p.y))}};
 const update=(d:Drawing,force=false)=>{value.current=d;setDrawing(d);if(force||Date.now()-lastSave.current>100){lastSave.current=Date.now();change.current(d)}};
 const down=(event:PointerEvent<SVGSVGElement>)=>{if(gesture.current||event.button!==0)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);const before=value.current,p=point(event);if(tool==='eraser'){gesture.current={pointerId:event.pointerId,before};update(eraseAt(before,p,size*3),true)}else{const stroke:Stroke={id:crypto.randomUUID(),tool,color,width:tool==='marker'?size*5:tool==='pencil'?size*.6:size,opacity:tool==='marker'?.28:tool==='pencil'?.7:1,points:[p]};gesture.current={pointerId:event.pointerId,before,stroke};update({...before,strokes:[...before.strokes,stroke]},true)}};
 const move=(event:PointerEvent<SVGSVGElement>)=>{const active=gesture.current;if(!active||active.pointerId!==event.pointerId)return;const p=point(event);if(active.stroke){const points=active.stroke.points;if(Math.hypot(p.x-points[points.length-1].x,p.y-points[points.length-1].y)<1)return;active.stroke={...active.stroke,points:[...points,p]};update({...active.before,strokes:[...active.before.strokes,active.stroke]})}else update(eraseAt(value.current,p,size*3))};
 return <div className="drawing-overlay drawing-inline-overlay" onMouseDown={e=>e.stopPropagation()}><section role="dialog" aria-modal="true" aria-label="Рисование" className="drawing-editor" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redoStroke();else undoStroke()}if(e.key==='Tab'){const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input'));const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}>
 <div className="drawing-header"><span>Рисование</span><div><button title="Отменить" aria-label="Отменить штрих" disabled={!undo.length} onClick={undoStroke}><Undo2 size={21}/></button><button title="Повторить" aria-label="Повторить штрих" disabled={!redo.length} onClick={redoStroke}><Redo2 size={21}/></button><button autoFocus className="drawing-done" aria-label="Готово" onClick={close}><Check size={23}/></button></div></div>
 <div className="drawing-paper"><svg className={'drawing-canvas '+tool} role="img" aria-label="Холст для рисования" viewBox={`0 0 ${drawing.width} ${drawing.height}`} onPointerDown={down} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish}><Strokes drawing={drawing}/></svg></div>
 <div className="drawing-tools" role="toolbar" aria-label="Инструменты рисования"><label className="drawing-color" title="Цвет"><input type="color" aria-label="Цвет рисунка" value={color} onChange={e=>setColor(e.target.value)}/></label>{([{id:'pencil',label:'Карандаш',Icon:Pencil},{id:'pen',label:'Перо',Icon:PenTool},{id:'marker',label:'Маркер',Icon:Highlighter},{id:'eraser',label:'Ластик — удалить штрих',Icon:Eraser}] as const).map(({id,label,Icon})=><button key={id} className={tool===id?'selected':''} title={label} aria-label={label} aria-pressed={tool===id} onClick={()=>setTool(id)}><Icon size={24}/></button>)}<label className="drawing-size">Толщина<input type="range" aria-label="Толщина линии" min="1" max="16" value={size} onChange={e=>setSize(Number(e.target.value))}/><span>{size}</span></label></div>
 </section></div>
}
